# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3Gp1JgFnXXu5uFWVIg5F8lHU631AV3n
"""

# from google.colab import drive
# drive.mount('/content/drive')

# import os
# os.chdir("/content/drive/MyDrive/Telecom_Intelligent_Assistant")

# !pip install -r /content/drive/MyDrive/Telecom_Intelligent_Assistant/requirements.txt

# !pip install -U transformers accelerate
# !pip install silma-tts --no-deps
# !pip install silma-tts
# !pip install -U transformers accelerate
# !pip install unstructured-inference --no-deps
# !pip install unstructured[all-local]
# !pip install gradio -q
# !pip install -U bitsandbytes>=0.46.1
# !pip install speechbrain

# pwd

# from huggingface_hub import login
# login(token="")

# !python app_gradio.py

# from faster_whisper import WhisperModel
# from faster_whisper.audio import decode_audio
# import torch
# from transformers import AutoProcessor, CohereAsrForConditionalGeneration
# from transformers.audio_utils import load_audio


# class ASR:
#     def __init__(
#         self,
#         model_name: str    = "base",
#         device: str        = "cuda",
#         compute_type: str  = "int8",
#     ):
#         # Remove the trailing comma after the processor initialization
#         self.processor = AutoProcessor.from_pretrained("namaa-space/cohere-transcribe-arabic-07-2026-int4")
#         self.asr_model = CohereAsrForConditionalGeneration.from_pretrained(
#             "namaa-space/cohere-transcribe-arabic-07-2026-int4",
#             device_map="auto"
#         )

#         if device == "cuda" and not torch.cuda.is_available():
#             print("CUDA is not available. Falling back to CPU.")
#             device = "cpu"

#         self.device = device
#         self.compute_type = compute_type

#         self.model = WhisperModel(
#             model_name,
#             device=device,
#             compute_type=compute_type,
#         )

#         print(f"Loaded Faster-Whisper model: {model_name}")
#         print(f"Device: {device}")
#         print(f"Compute Type: {compute_type}")

#         if device == "cuda":
#             print(f"GPU: {torch.cuda.get_device_name(0)}")

#     def detect_language(self, audio_path):
#         audio = decode_audio(audio_path, sampling_rate=self.model.feature_extractor.sampling_rate)
#         language, language_probability, all_language_probs = self.model.detect_language(audio)
#         lang_probs = dict(all_language_probs)
#         en_prob = lang_probs.get("en", 0.0)
#         ar_prob = lang_probs.get("ar", 0.0)
#         if ar_prob >= en_prob:
#             selected_lang = "ar"
#             selected_prob = ar_prob
#         else:
#             selected_lang = "en"
#             selected_prob = en_prob

#         return selected_lang

#     def transcribe(
#         self,
#         audio_path: str,
#         beam_size: int = 5,
#     ):
#         language_audio = self.detect_language(audio_path)
#         print(f"Detected language: {language_audio}")

#         audio = load_audio(audio_path, sampling_rate=16000)
#         inputs = self.processor(
#             audio,
#             sampling_rate=16000,
#             language=language_audio,
#             return_tensors="pt"
#         ).to(device=self.asr_model.device, dtype=self.asr_model.dtype)

#         outputs = self.asr_model.generate(**inputs, max_new_tokens=256)

#         # Decode the outputs
#         transcription = self.processor.batch_decode(outputs, skip_special_tokens=True)

#         return {
#             "language": language_audio,
#             "language_probability": 100,  # You might want to calculate this properly
#             "segments": outputs,
#             "text": transcription[0] if transcription else "",
#         }

